Ensemble capability for single-step training
NCAR/miles-credit pull request #137
Opened 2024-12-20 00:14 UTC by dkimpara

- supports batch_size > 1
- currently only KCRPS (unbiased CRPS) available

Testing (on casper)

`applications/train.py -c config/test_cesm_ensemble.yml -l 1`

2024-12-25 15:48 UTC, jsschreck commented
@dkimpara the batch_size > 1 ... is this meaning it will support the new datasets I added, or are you doing it yourself here?

2024-12-25 16:12 UTC, dkimpara commented
I haven't yet configured it for your datasets. I will do that once your PR
is settled. What I meant was that the ensemble features are compatible with
batches with more than one target
Dhamma Kimpara

PhD Candidate in Computer Science
National Center for Atmospheric Research, and University of Colorado Boulder
Pronouns in use: He/Him/His

On Wed, Dec 25, 2024, 8:48 AM jsschreck ***@***.***> wrote:

> @dkimpara <https://github.com/dkimpara> the batch_size > 1 ... is this
> meaning it will support the new datasets I added, or are you doing it
> yourself here?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NCAR/miles-credit/pull/137#issuecomment-2561934532>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD7CU77BITFFQ74LMAIHYN32HLHVXAVCNFSM6AAAAABT6B75GKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRRHEZTINJTGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-26 20:58 UTC, jsschreck commented
@dkimpara trainerERA5_v2.py will be deprecated in my PR; we will only need trainerERA5_multistep_grad_accum.py going forward, so you should add the ensemble change to that script as well. Keep what you have b/c I am not going to remove _v2 just yet since other people are still using it.

2024-12-29 05:04 UTC, yingkaisha requested changes
Finished review

2024-12-29 05:04 UTC, yingkaisha commented on credit/trainers/trainerERA5_v2.py
> +
This place can have an if condition, so the deterministic training routine will not touch this part.

2024-12-29 05:04 UTC, yingkaisha commented on credit/trainers/trainerERA5_v2.py
> +
if condition

2024-12-29 05:04 UTC, yingkaisha commented on credit/metrics.py
> +
This place can have an if condition, so the deterministic training routine will not touch this part.

2024-12-29 05:04 UTC, yingkaisha commented on credit/parser.py
> +            conf["trainer"]["ensemble_size"] = 1
Can you have an option is skip the ensemble routine? For those who do not use ensemble training, going through the ensemble code can cause a slow down.

2025-01-01 18:53 UTC, jsschreck commented on credit/metrics.py
> +        self.ensemble_size = conf["trainer"]["ensemble_size"]
If I do not use ensemble_size this will fail here. Prob better to have something like "if ensemble_size in conf["trainer"] conditional

2025-01-01 18:53 UTC, jsschreck commented on credit/metrics.py
> +
Yeah -- will also fail here.

2025-01-16 20:27 UTC, dkimpara commented on credit/parser.py
> +            conf["trainer"]["ensemble_size"] = 1
I will make sure ensemble_size=1 (deterministic) doesn't trigger the ensemble code

2025-01-16 20:28 UTC, dkimpara commented on credit/metrics.py
> +        self.ensemble_size = conf["trainer"]["ensemble_size"]
I've set the default ensemble_size to be 1 (meaning deterministic) in the parser. IMO for code clarity it's easier to deal with having an argument always exist rather than not

2025-01-16 20:38 UTC, dkimpara commented
@jsschreck @yingkaisha 
looking at the new codebase with many new training options, would it be better to add ensembling code to dataloaders? what do you all think?

2025-01-16 20:42 UTC, dkimpara commented
> @jsschreck @yingkaisha looking at the new codebase with many new training options, would it be better to add ensembling code to dataloaders? what do you all think?

oof. nevermind. i took a look at the datasets code. looks pretty complex

2025-01-16 21:27 UTC, dkimpara commented on credit/metrics.py
> +        self.ensemble_size = conf["trainer"]["ensemble_size"]
nevermind. I think i'll add it just to be safe. we might have different parsers going around

2025-01-16 23:33 UTC, dkimpara commented on credit/parser.py
> +            conf["trainer"]["ensemble_size"] = 1
see parser and new if statements

2025-01-17 17:24 UTC, yingkaisha commented
I will do the review by Monday

2025-01-20 06:48 UTC, yingkaisha commented
Looks good to me

2025-01-20 06:48 UTC, yingkaisha approved these changes

2025-01-22 22:42 UTC, jsschreck approved these changes

2025-01-22 22:42 UTC, merged