TOA var and Quantile scaling,
NCAR/miles-credit pull request #37
Opened 2024-03-30 17:59 UTC by WillyChap

This PR adds the TOA predictor variable. It comes in as another returned item to the to_tensor dict (return_dict['TOA']). Additionally it adds the new quantile scaling and the dictionary. 

I tried to speed it up... but to no end. Please adjust @djgagne if you see anything to boost performance. I know we don't have to do the transform 1 time chunk at a time with the bridge scaler, but changing that offers almost no speedup, and the concat is fast. 

Additionally I've added a transforms notebook for rapid testing/development of the transforms 

![image](https://github.com/NCAR/miles-credit/assets/14932329/b7298906-828c-457b-92f0-52175fe554e5)

2024-03-30 21:34 UTC, djgagne requested changes
The best way to speed up the quantile transform process for training is to pre-scale all ERA5 data, which should be much more straightforward to do. Another option would be to reserve some MPI ranks for scaling purposes and add MPI commands to send tensor data to those ranks for transforms. I could potentially store a scaled version of ERA5 but would need to expand my scratch quota first.

2024-03-30 21:34 UTC, djgagne commented on credit/transforms.py
> +        rscal_3d = (np.array(x[:, :(len(self.variables)*self.levels), :, :]))
Instead doing `np.array(x[...])` do `x.numpy()`, which returns a view instead of a copy.

2024-03-30 21:34 UTC, djgagne commented on credit/transforms.py
> +        transformed_tensor[:, :, :, :] = torch.tensor((self.scaler_3d.inverse_transform(rscal_3d))).to(device)
If you want to try doing the transform in parallel, there is a `pool=` kwarg for QuantileScaler inverse_transform and transform that uses a multiprocessing Pool to perform parallel transforms across variables. However, I have found that it doesn't necessarily play nicely with MPI, which is being used under the hood for distributed training.

2024-03-30 21:34 UTC, djgagne commented on credit/transforms.py
> +                    value['U'].sel(time=time)[:,:,:]=(TTtrans[:,:self.levels,:,:].squeeze())
.sel is generally much slower than .loc.

2024-03-30 21:34 UTC, djgagne commented on config/crossformer.yml
> +    static_variables: ['Z_GDS4_SFC','LSM','tsi'] # []
John's staging on scratch is missing a few years of ERA5 data compared with Will's directory on campaign.

2024-03-30 21:49 UTC, djgagne commented
I just emailed CISL help to see if I could get my derecho scratch quota upped to 100 TB so I can store the quantile-scaled ERA5 data.

2024-04-03 16:25 UTC, jsschreck commented on config/crossformer.yml
> +    static_variables: ['Z_GDS4_SFC','LSM','tsi'] # []
Yeah Will had to redo a few years after the fact; I'll copy the missing ones over now.

2024-04-16 20:14 UTC, jsschreck approved these changes

2024-04-16 20:14 UTC, merged